#!/bin/sh
set -eu

token_file=$1
config_file=$2
token=$(/bin/dd if="$token_file" 2>/dev/null)
/bin/rm -f -- "$token_file"
if [ -z "$token" ]; then
    echo 'Enrollment token is empty.' >&2
    exit 2
fi
SCANNER_ENROLLMENT_TOKEN=$token
export SCANNER_ENROLLMENT_TOKEN
token=
set +e
'/Library/Application Support/EndpointScanner/bin/endpoint-scanner' enroll \
    --config "$config_file"
status=$?
set -e
unset SCANNER_ENROLLMENT_TOKEN
exit "$status"
